version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "movies_database"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: 1234

    ports:
      - "5432:5432"
    volumes:
        - ./:/app
